export {Home} from "./Home";
export {Baki} from "./Baki";
export {LoginPage} from "./LoginPage";
export {SignupPage} from "./SignupPage";
export {Firdevsi} from "./Firdevsi";
export {Hayyam} from "./Hayyam";
export {Mevlana} from "./Mevlana";
export {Sadi} from "./Sadi";
export {Hafız} from "./Hafız";
